name: usaid_project
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Service locator
  get_it: ^3.1.0
  # Bloc for state management
  flutter_bloc: ^3.0.0
  flutter_rating_bar: ^3.2.0+1
  # Value equality
  equatable: ^1.0.1
  # Functional programming thingises
  dartz: ^0.8.9
  bubble_tab_indicator: ^0.1.4
  # Remote API
  data_connection_checker: ^0.3.4
  http: ^0.12.0+4
  fl_chart: ^0.9.4
  # Local cache
  shared_preferences: ^0.5.6
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  #firebase ml
  firebase_ml_vision: ^0.7.0
  flutter_svg: ^0.19.1
  camera: ^0.5.8+7
  #location
  location: ^3.0.0
  #image_convert
  image: ^2.1.4
  path:
  cached_network_image: ^2.2.0
  flutter_datetime_picker: ^1.4.0
  carousel_slider: ^2.3.1
  #signalR
  signalr_core: ^1.0.7
  google_fonts: ^1.1.2
  logging: ^0.11.4
  #face
  path_provider: ^1.6.11
  tflite_flutter: ^0.5.0
  #notify
  flutter_local_notifications: ^1.4.4+1
  #forefround service
  #  foreground_service: ^2.0.1+1
  #  flutter_foreground_plugin: ^0.6.0
  google_maps_flutter: ^1.0.6
  #progress bar
  percent_indicator: ^2.1.8
  #calender
  date_format: ^1.0.9
  syncfusion_flutter_calendar: ^18.4.49
  #excel
  data_tables: ^1.0.3
  #table
  horizontal_data_table: ^1.0.8
  #dialog
  flutter_custom_dialog: ^1.0.20
  modal_bottom_sheet: ^1.0.0+1
  #android intent
  commons: ^0.7.8+3
  #  android_intent: ^0.3.7+7
  #paint
  painter: ^0.4.0
  flutter_colorpicker: ^0.3.5
  intl: ">=0.14.0"
  fluttertoast: ^7.1.8
  flutter_countdown_timer: ^3.0.1
  flutter_slidable: ^0.5.7
  device_info: ^0.4.2+10
  tiengviet: ^0.4.1
  flutter_custom_clippers: ^1.1.2
  url_launcher: ^5.7.10
  #input code validation
  pin_code_fields: ^6.1.0
  flare_flutter: ^2.0.6
  upgrader: ^2.8.3


dev_dependencies:
  flutter_test:
    sdk: flutter
    
flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/logos/